### ISSUE TITLE
Handle private repos on "PubValidate"

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/gin-valid#11]
When a repository is validated using ServiceWaiter via `web/validate.go:PubValidate`, only public repositories should be validated.

If we ever encounter a private repository in this route, fail with `http.StatusUnauthorized` and log all details.

**Comment by achilleas-k** [comment]
Closed by #16 (see 9b9ecaac82195d554e2c224a83d01dba2cd93ec3).
