### ISSUE TITLE
BIDS validation on a non-BIDS repo results in a blank 500 page

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/gin-valid#74]
When running a validation on a non-BIDS repository, the "Results" page should not be a blank 500 page, but a full gin-valid page with an appropriate issue description and an option to return to the "one-time validation" or validator listing page.

**Comment by pavelsne** [comment]
I fixed that by showing the error in the one-time-validation form but the solution doesn't cover exactly the issue description. And we were thinking about ajax...
